# Generated by Django 4.1.3 on 2022-11-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_id", models.IntegerField()),
                ("title", models.CharField(max_length=155)),
                ("description", models.CharField(max_length=5000)),
                ("type", models.CharField(max_length=12)),
            ],
        ),
    ]
